// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMZlqnN4njc6ROlN0sYnPOiIjGRsYIig',
    appId: '1:296422087015:web:05f1daa2d04650e7d237c2',
    messagingSenderId: '296422087015',
    projectId: 'note-app-53a97',
    authDomain: 'note-app-53a97.firebaseapp.com',
    storageBucket: 'note-app-53a97.firebasestorage.app',
    measurementId: 'G-7LSMN8YMRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDyb07vEyMyzLMVUqaZIcIxkOUwl1cjJw',
    appId: '1:296422087015:android:59e7c9f8b84af664d237c2',
    messagingSenderId: '296422087015',
    projectId: 'note-app-53a97',
    storageBucket: 'note-app-53a97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJWgP0uXkBAF_wM6VOGGi4moc4-H_e-IY',
    appId: '1:296422087015:ios:65469512f2cd78d5d237c2',
    messagingSenderId: '296422087015',
    projectId: 'note-app-53a97',
    storageBucket: 'note-app-53a97.firebasestorage.app',
    iosBundleId: 'com.example.googleButton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJWgP0uXkBAF_wM6VOGGi4moc4-H_e-IY',
    appId: '1:296422087015:ios:65469512f2cd78d5d237c2',
    messagingSenderId: '296422087015',
    projectId: 'note-app-53a97',
    storageBucket: 'note-app-53a97.firebasestorage.app',
    iosBundleId: 'com.example.googleButton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJMZlqnN4njc6ROlN0sYnPOiIjGRsYIig',
    appId: '1:296422087015:web:afded3ce66d352afd237c2',
    messagingSenderId: '296422087015',
    projectId: 'note-app-53a97',
    authDomain: 'note-app-53a97.firebaseapp.com',
    storageBucket: 'note-app-53a97.firebasestorage.app',
    measurementId: 'G-7EXHRX2WEV',
  );
}
